// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yqasidudmgpolryxtxse.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlxYXNpZHVkbWdwb2xyeXh0eHNlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg0MzQ1MjAsImV4cCI6MjA4NDAxMDUyMH0.XGnhpxR3kbk7HktxtkO6KLpcM9I6AvP7ZsTv04frP0s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});